export const myProject = [{ project_title: "react project", category: ["React"], imgPath : "./images/1.jpg"},
{ project_title: "react & css project", category: ["react", "css"], imgPath: "./images/2.jpg" },
{ project_title: "css project", category: ["css"], imgPath: "./images/3.jpg" },
{ project_title: "react project", category: ["React"], imgPath: "./images/4.jpg" },
{ project_title: "css projects", category: ["css"], imgPath: "./images/5.jpg" },
{ project_title: "javascript project", category: ["java"], imgPath: "./images/6.jpg" },
{ project_title: "node projrct", category: ["node"], imgPath: "./images/7.jpg" },
{ project_title: "node project2", category: ["node"], imgPath: "./images/8.jpg" },
{ project_title: "java script", category: ["java"], imgPath: "./images/9.jpg" },
]
